import { prisma } from "../prisma";

const VERBOSE_PIPELINE_LOGS = process.env.NUXT_PIPELINE_VERBOSE_LOGS === "true";

const ESSENTIAL_AGENT_LOG_STATUSES = new Set([
  "PIPELINE_STARTED",
  "PIPELINE_FINISHED",
  "SOURCE_NOT_FOUND",
  "SOURCE_FETCH_EXCEPTION",
  "SOURCE_FETCH_BLOCKED_SECURITY",
  "HTML_FALLBACK_EXCEPTION",
  "ARTICLE_INSERT_FAILED",
  "RSS_REIMPORT_STARTED",
  "RSS_REIMPORT_FINISHED",
  "SCOPED_RSS_AUDIT_STARTED",
  "SCOPED_RSS_AUDIT_FINISHED",
  "ROOT_DISCOVERY_COMPLETED",
  "CATEGORY_DISCOVERY_STARTED",
  "CATEGORY_DISCOVERY_COMPLETED",
  "CATEGORY_DISCOVERY_FAILED",
  "CATEGORY_FEED_USED",
  "CATEGORY_FEED_FALLBACK_TO_ROOT",
  "FEED_ALREADY_SEEN_SUMMARY",
  "ARTICLE_ENRICHMENT_STARTED",
  "ARTICLE_ENRICHMENT_FINISHED",
  "ARTICLE_CONTENT_ENRICHMENT_STARTED",
  "ARTICLE_CONTENT_ENRICHMENT_FINISHED",
  "ARTICLE_DISCOVERY_STARTED",
  "ARTICLE_DISCOVERY_BATCH_STARTED",
  "ARTICLE_DISCOVERY_BATCH_FINISHED",
  "ARTICLE_DISCOVERY_COMPLETED",
  "ARTICLE_DISCOVERY_FAILED",
  "ARTICLE_DISCOVERY_SKIPPED",
  "BROWSER_RESOLUTION_STARTED",
  "BROWSER_RESOLUTION_CANDIDATES_FOUND",
  "BROWSER_RESOLUTION_RESOLVED",
  "BROWSER_RESOLUTION_FAILED",
  "BROWSER_RESOLUTION_NO_CANDIDATES",
  "BROWSER_RESOLUTION_ALL_DUPLICATES",
  "BROWSER_RESOLUTION_VERIFICATION_FAILED",
  "HARD_CASE_CHAIN_PIPELINE_STARTED",
  "HARD_CASE_CHAIN_PIPELINE_FINISHED",
  "HARD_CASE_CHAIN_PIPELINE_SKIPPED",
]);

const isPersistedAgentLogStatus = (status: string) =>
  VERBOSE_PIPELINE_LOGS || ESSENTIAL_AGENT_LOG_STATUSES.has(status);

export const getAgentLogPrefix = (status: string) => {
  if (
    [
      "PIPELINE_STARTED",
      "PIPELINE_FINISHED",
      "SOURCE_NOT_FOUND",
      "SOURCE_FETCH_EXCEPTION",
      "SOURCE_FETCH_BLOCKED_SECURITY",
      "HTML_FALLBACK_EXCEPTION",
      "RSS_REIMPORT_STARTED",
      "RSS_REIMPORT_FINISHED",
      "SCOPED_RSS_AUDIT_STARTED",
      "SCOPED_RSS_AUDIT_FINISHED",
      "ROOT_DISCOVERY_COMPLETED",
      "CATEGORY_DISCOVERY_STARTED",
      "CATEGORY_DISCOVERY_COMPLETED",
      "CATEGORY_DISCOVERY_FAILED",
      "CATEGORY_FEED_USED",
      "CATEGORY_FEED_FALLBACK_TO_ROOT",
      "FEED_ALREADY_SEEN_SUMMARY",
      "HARD_CASE_DISCOVERY_QUEUED",
      "HARD_CASE_CHAIN_PIPELINE_STARTED",
      "HARD_CASE_CHAIN_PIPELINE_FINISHED",
      "HARD_CASE_CHAIN_PIPELINE_SKIPPED",
      "BROWSER_RESOLUTION_STARTED",
      "BROWSER_RESOLUTION_CANDIDATES_FOUND",
      "BROWSER_RESOLUTION_RESOLVED",
      "BROWSER_RESOLUTION_FAILED",
      "BROWSER_RESOLUTION_NO_CANDIDATES",
      "BROWSER_RESOLUTION_ALL_DUPLICATES",
      "BROWSER_RESOLUTION_VERIFICATION_FAILED",
    ].includes(status)
  ) {
    return "A1";
  }

  if (
    [
      "ARTICLE_DISCOVERY_STARTED",
      "ARTICLE_DISCOVERY_BATCH_STARTED",
      "ARTICLE_DISCOVERY_BATCH_FINISHED",
      "ARTICLE_DISCOVERY_COMPLETED",
      "ARTICLE_DISCOVERY_FAILED",
      "ARTICLE_DISCOVERY_SKIPPED",
    ].includes(status)
  ) {
    return "A2";
  }

  if (
    [
      "ARTICLE_ENRICHMENT_STARTED",
      "ARTICLE_ENRICHMENT_FINISHED",
      "ARTICLE_CONTENT_ENRICHMENT_STARTED",
      "ARTICLE_CONTENT_ENRICHMENT_FINISHED",
    ].includes(status)
  ) {
    return "A3";
  }

  return "A?";
};

export async function logAgentScan(input: {
  status: string;
  executionTimeMs: number;
  sourceId?: string | null;
  categoryId?: string | null;
  errorLog?: string | null;
}) {
  if (!isPersistedAgentLogStatus(input.status)) {
    return;
  }

  await prisma.agentScanLog.create({
    data: {
      sourceId: input.sourceId || null,
      categoryId: input.categoryId || null,
      status: input.status,
      executionTimeMs: input.executionTimeMs,
      errorLog: input.errorLog || null,
    },
  });
}
