export const NOTIFICATION_WORKFLOW_STATUSES = [
  "NOTIFICATION_WORKFLOW_SCHEDULED",
  "NOTIFICATION_WORKFLOW_ACTIVE",
  "NOTIFICATION_WORKFLOW_COMPLETED",
  "NOTIFICATION_WORKFLOW_COMPLETED_WITH_ERRORS",
  "NOTIFICATION_WORKFLOW_FAILED",
  "NOTIFICATION_WORKFLOW_FAILED_RETRYABLE",
  "NOTIFICATION_WORKFLOW_RECONCILIATION_REQUIRED",
  "NOTIFICATION_WORKFLOW_ABANDONED",
  "NOTIFICATION_WORKFLOW_EXHAUSTED",
] as const;

export const NOTIFICATION_RECONCILIATION_CONFIRMATION = "RECONCILE_NOTIFICATION_WORKFLOW_MARKER";

export function utcDateKey(date: Date): string {
  return date.toISOString().slice(0, 10);
}
